import { ExportData } from '@/types/export'

export const generatePDF = async (exportData: ExportData): Promise<Blob> => {
  // In a real implementation, you would use a PDF library like jsPDF or pdf-lib
  // For now, we'll create a simple HTML-based PDF using browser print functionality
  const htmlContent = generatePDFHTML(exportData)
  
  // Create a blob from HTML content
  const blob = new Blob([htmlContent], { type: 'text/html' })
  return blob
  
  // Note: For proper PDF generation in production, consider:
  // - Using a server-side PDF generation service
  // - Using a library like jsPDF with html2canvas
  // - Using a headless browser service
}

const generatePDFHTML = (exportData: ExportData): string => {
  const { tasks, summary, metadata } = exportData
  
  const groupedTasks = tasks.reduce((acc, task) => {
    const category = task.category || 'Uncategorized'
    if (!acc[category]) {
      acc[category] = []
    }
    acc[category].push(task)
    return acc
  }, {} as Record<string, any[]>)

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Compliance Report - ${metadata.businessName}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 40px;
      color: #333;
    }
    .header {
      border-bottom: 2px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .company-name {
      font-size: 24px;
      font-weight: bold;
      color: #2563eb;
    }
    .report-title {
      font-size: 18px;
      margin: 10px 0;
    }
    .metadata {
      font-size: 12px;
      color: #666;
    }
    .summary {
      background: #f8fafc;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 15px;
    }
    .summary-item {
      text-align: center;
    }
    .summary-value {
      font-size: 24px;
      font-weight: bold;
      color: #2563eb;
    }
    .summary-label {
      font-size: 12px;
      color: #666;
      margin-top: 5px;
    }
    .category-section {
      margin-bottom: 30px;
    }
    .category-title {
      font-size: 16px;
      font-weight: bold;
      background: #e2e8f0;
      padding: 10px 15px;
      border-radius: 4px;
      margin-bottom: 15px;
    }
    .task-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
    }
    .task-table th {
      background: #f1f5f9;
      padding: 8px 12px;
      text-align: left;
      border: 1px solid #e2e8f0;
    }
    .task-table td {
      padding: 8px 12px;
      border: 1px solid #e2e8f0;
    }
    .status-completed {
      color: #059669;
      font-weight: bold;
    }
    .status-pending {
      color: #d97706;
      font-weight: bold;
    }
    .priority-high { color: #dc2626; }
    .priority-medium { color: #d97706; }
    .priority-low { color: #059669; }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      font-size: 10px;
      color: #666;
      text-align: center;
    }
    @media print {
      body { margin: 20px; }
      .summary-grid { grid-template-columns: repeat(5, 1fr); }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company-name">${metadata.businessName}</div>
    <div class="report-title">Compliance Tasks Report</div>
    <div class="metadata">
      Date Range: ${metadata.dateRange} | 
      Exported: ${new Date(metadata.exportedAt).toLocaleDateString()} | 
      Generated by Compliance Track
    </div>
  </div>

  <div class="summary">
    <div class="summary-grid">
      <div class="summary-item">
        <div class="summary-value">${summary.total}</div>
        <div class="summary-label">Total Tasks</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${summary.completed}</div>
        <div class="summary-label">Completed</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${summary.pending}</div>
        <div class="summary-label">Pending</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${summary.overdue}</div>
        <div class="summary-label">Overdue</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${summary.completionRate}%</div>
        <div class="summary-label">Completion Rate</div>
      </div>
    </div>
  </div>

  ${Object.entries(groupedTasks).map(([category, categoryTasks]) => `
    <div class="category-section">
      <div class="category-title">${category} (${categoryTasks.length} tasks)</div>
      <table class="task-table">
        <thead>
          <tr>
            <th>Task Name</th>
            <th>Type</th>
            <th>Status</th>
            <th>Priority</th>
            <th>Due Date</th>
            <th>Completed</th>
          </tr>
        </thead>
        <tbody>
          ${categoryTasks.map(task => `
            <tr>
              <td>${task.task_name}</td>
              <td>${task.type}</td>
              <td class="status-${task.status}">${task.status.charAt(0).toUpperCase() + task.status.slice(1)}</td>
              <td class="priority-${task.priority}">${task.priority.charAt(0).toUpperCase() + task.priority.slice(1)}</td>
              <td>${new Date(task.due_date).toLocaleDateString()}</td>
              <td>${task.completed_at ? new Date(task.completed_at).toLocaleDateString() : '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
  `).join('')}

  <div class="footer">
    This report was generated by Compliance Track — by GreenAI Analytics on ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `
}

// Alternative: Client-side PDF generation using jsPDF (if you prefer)
export const generatePDFWithJSPDF = async (exportData: ExportData): Promise<Blob> => {
  // This would require installing jsPDF: npm install jspdf
  // And possibly jspdf-autotable for tables: npm install jspdf-autotable
  
  // For now, we'll return a simple implementation
  // In production, you would implement proper PDF generation
  
  const htmlContent = generatePDFHTML(exportData)
  return new Blob([htmlContent], { type: 'text/html' })
}